// generated by src/routes/package.gen.ts

import type {Package_Json} from '@ryanatkn/belt/package_json.js';
import type {Src_Json} from '@ryanatkn/belt/src_json.js';

export const package_json: Package_Json = {
	name: '@ryanatkn/fuz_blog',
	version: '0.14.0',
	description: 'blog software from scratch with SvelteKit',
	glyph: '🖊️',
	logo: 'logo.svg',
	logo_alt: 'a friendly yellow spider facing you',
	public: true,
	homepage: 'https://blog.fuz.dev/',
	repository: 'https://github.com/ryanatkn/fuz_blog',
	scripts: {
		start: 'gro dev',
		dev: 'gro dev',
		build: 'gro build',
		check: 'gro check',
		test: 'gro test',
		preview: 'vite preview',
		deploy: 'gro deploy',
	},
	type: 'module',
	engines: {node: '>=22.15'},
	peerDependencies: {
		'@ryanatkn/belt': '*',
		'@ryanatkn/fuz': '*',
		'@ryanatkn/fuz_mastodon': '*',
		'@ryanatkn/gro': '*',
		'@ryanatkn/moss': '*',
		'@sveltejs/kit': '^2',
		'date-fns': '^4',
		svelte: '^5',
	},
	devDependencies: {
		'@changesets/changelog-git': '^0.2.1',
		'@ryanatkn/belt': '^0.34.1',
		'@ryanatkn/eslint-config': '^0.8.0',
		'@ryanatkn/fuz': '^0.146.0',
		'@ryanatkn/fuz_code': '^0.26.0',
		'@ryanatkn/fuz_mastodon': '^0.32.0',
		'@ryanatkn/gro': '^0.167.1',
		'@ryanatkn/moss': '^0.36.0',
		'@sveltejs/adapter-static': '^3.0.9',
		'@sveltejs/kit': '^2.37.1',
		'@sveltejs/package': '^2.5.0',
		'@sveltejs/vite-plugin-svelte': '^6.1.4',
		'@types/node': '^24.3.1',
		'date-fns': '^4.1.0',
		eslint: '^9.35.0',
		'eslint-plugin-svelte': '^3.12.2',
		prettier: '^3.6.2',
		'prettier-plugin-svelte': '^3.4.0',
		svelte: '^5.38.7',
		'svelte-check': '^4.3.1',
		tslib: '^2.8.1',
		typescript: '^5.9.2',
		'typescript-eslint': '^8.42.0',
		vitest: '^3.2.4',
	},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [{files: 'package.json', options: {useTabs: false}}],
	},
	sideEffects: ['**/*.css'],
	files: ['dist'],
	exports: {
		'./package.json': './package.json',
		'./*.js': {types: './dist/*.d.ts', default: './dist/*.js'},
		'./*.svelte': {
			types: './dist/*.svelte.d.ts',
			svelte: './dist/*.svelte',
			default: './dist/*.svelte',
		},
	},
} as any;

export const src_json: Src_Json = {
	name: '@ryanatkn/fuz_blog',
	version: '0.14.0',
	modules: {
		'./blog_helpers.js': {
			path: 'blog_helpers.ts',
			declarations: [
				{name: 'resolve_blog_post_item', kind: 'function'},
				{name: 'collect_blog_post_ids', kind: 'function'},
				{name: 'load_blog_post_modules', kind: 'function'},
				{name: 'to_next_blog_post_id', kind: 'function'},
				{name: 'to_blog_post_path', kind: 'function'},
			],
		},
		'./blog.gen.js': {path: 'blog.gen.ts', declarations: [{name: 'gen', kind: 'function'}]},
		'./blog.js': {
			path: 'blog.ts',
			declarations: [
				{name: 'Blog_Feed_Data', kind: 'type'},
				{name: 'Blog_Feed', kind: 'type'},
				{name: 'Blog_Post_Data', kind: 'type'},
				{name: 'Blog_Comments', kind: 'type'},
				{name: 'Mastodon_Blog_Comments', kind: 'type'},
				{name: 'Blog_Module', kind: 'type'},
				{name: 'Blog_Post_Module', kind: 'type'},
				{name: 'Blog_Post_Id', kind: 'type'},
				{name: 'Blog_Post_Item', kind: 'type'},
				{name: 'blog_feed_context', kind: 'variable'},
			],
		},
		'./feed.js': {
			path: 'feed.ts',
			declarations: [
				{name: 'Feed', kind: 'type'},
				{name: 'Feed_Item', kind: 'type'},
				{name: 'create_atom_feed', kind: 'function'},
			],
		},
		'./post.task.js': {path: 'post.task.ts', declarations: [{name: 'task', kind: 'variable'}]},
		'./update_post.task.js': {
			path: 'update_post.task.ts',
			declarations: [{name: 'task', kind: 'variable'}],
		},
		'./util.js': {
			path: 'util.ts',
			declarations: [
				{name: 'format_date', kind: 'function'},
				{name: 'to_pathname', kind: 'function'},
			],
		},
		'./Blog_Post_Header.svelte': {
			path: 'Blog_Post_Header.svelte',
			declarations: [{name: 'default', kind: 'component'}],
		},
		'./Blog_Post.svelte': {
			path: 'Blog_Post.svelte',
			declarations: [{name: 'default', kind: 'component'}],
		},
		'./Feed_Item_Date.svelte': {
			path: 'Feed_Item_Date.svelte',
			declarations: [{name: 'default', kind: 'component'}],
		},
		'./Hash_Link.svelte': {
			path: 'Hash_Link.svelte',
			declarations: [{name: 'default', kind: 'component'}],
		},
	},
} as any;

// generated by src/routes/package.gen.ts
